[workspace]
channels = ["conda-forge", "pytorch"]
name = "vietnamese-mathocr-project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
torchvision = "*"
torchaudio = "*"
pandas = "*"
numpy = "<2.2"
tqdm = "*"
huggingface_hub = "*"
pillow = "*"
pyarrow = "*"
timm = "*"
pyturbojpeg = "*"
imagehash = "*"
opencv = ">=4.13.0,<5"
pytorch = ">=2.10.0,<3"
transformers = ">=5.2.0,<6"
datasets = ">=4.5.0,<5"
